// SPDX-License-Identifier: AGPL-3.0-only

package main

import (
	"bytes"
	"compress/gzip"
	"go/parser"
	"go/token"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const generated = `// Code generated by bpf2go; DO NOT EDIT.
//go:build amd64

package fixture
import (
	"bytes"
	_ "embed"
	"fmt"
	"github.com/cilium/ebpf"
)
func loadTest() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TestBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil { return nil, fmt.Errorf("can't load test: %w", err) }
	return spec, err
}
//go:embed test_bpfel.o
var _TestBytes []byte
`

func TestPackRoundTrip(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "test_bpfel.go")
	object := filepath.Join(dir, "test_bpfel.o")
	data := append([]byte("\x7fELF"), bytes.Repeat([]byte("BTF and relocation payload\x00"), 100)...)
	for path, data := range map[string][]byte{path: []byte(generated), object: data} {
		if err := os.WriteFile(path, data, 0600); err != nil {
			t.Fatal(err)
		}
	}
	if err := run([]string{filepath.Join(dir, "*_bpfel.go")}); err != nil {
		t.Fatal(err)
	}
	source, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := parser.ParseFile(token.NewFileSet(), path, source, parser.AllErrors); err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{"//go:build amd64", "//go:embed test_bpfel.o.gz", "bpfobject.Load(_TestBytes)"} {
		if !bytes.Contains(source, []byte(want)) {
			t.Fatalf("generated loader lost %q", want)
		}
	}
	compressed, err := os.ReadFile(object + ".gz")
	if err != nil {
		t.Fatal(err)
	}
	r, err := gzip.NewReader(bytes.NewReader(compressed))
	if err != nil {
		t.Fatal(err)
	}
	defer r.Close()
	restored, err := io.ReadAll(r)
	if err != nil || !bytes.Equal(restored, data) {
		t.Fatalf("object changed during compression: %v", err)
	}
	if err := pack(path); err != nil {
		t.Fatal(err)
	}
	for path, want := range map[string][]byte{path: source, object: data, object + ".gz": compressed} {
		got, err := os.ReadFile(path)
		if err != nil || !bytes.Equal(got, want) {
			t.Fatalf("second pack changed %s: %v", path, err)
		}
	}
}

func TestRejectUnknownTemplate(t *testing.T) {
	for _, source := range []string{
		strings.Replace(generated, "Code generated by bpf2go", "User-written code", 1),
		strings.Replace(generated, "reader :=", "reader =", 1),
		strings.Replace(generated, "test_bpfel.o", "../test_bpfel.o", 1),
		strings.Replace(generated, "//go:embed test_bpfel.o", "", 1),
	} {
		if _, _, err := rewrite([]byte(source)); err == nil {
			t.Fatal("accepted an unsupported generated loader")
		}
	}
}
