// SPDX-License-Identifier: AGPL-3.0-only

// dae-bpf-pack compresses bpf2go's embedded objects and updates its loaders.
// The original ELF files remain available for audits and kernel tooling.
package main

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

var (
	embedPattern  = regexp.MustCompile(`(?m)^//go:embed (\S+\.o)(\.gz)?$`)
	loaderPattern = regexp.MustCompile(`reader := bytes.NewReader\((\w+)\)\n\tspec, err := ebpf.LoadCollectionSpecFromReader\(reader\)`)
)

func rewrite(source []byte) ([]byte, string, error) {
	if !bytes.HasPrefix(source, []byte("// Code generated by bpf2go; DO NOT EDIT.")) {
		return nil, "", fmt.Errorf("expected bpf2go-generated source")
	}
	matches := embedPattern.FindAllSubmatch(source, -1)
	if len(matches) != 1 {
		return nil, "", fmt.Errorf("expected one embedded BPF object")
	}
	object := string(matches[0][1])
	if filepath.Base(object) != object {
		return nil, "", fmt.Errorf("expected an object in the generated file's directory")
	}
	if len(matches[0][2]) != 0 {
		return source, object, nil
	}
	// Fail if bpf2go's template changes, rather than silently embedding an
	// object that the generated loader cannot decode.
	if bytes.Count(source, []byte("\t\"bytes\"\n")) != 1 || bytes.Count(source, []byte(`"github.com/cilium/ebpf"`)) != 1 || len(loaderPattern.FindAll(source, -1)) != 1 {
		return nil, "", fmt.Errorf("unsupported bpf2go loader template")
	}
	source = bytes.Replace(source, []byte("\t\"bytes\"\n"), nil, 1)
	source = bytes.Replace(source, []byte(`"github.com/cilium/ebpf"`), []byte("\"github.com/cilium/ebpf\"\n\t\"github.com/daeuniverse/dae/internal/bpfobject\""), 1)
	source = loaderPattern.ReplaceAll(source, []byte(`spec, err := bpfobject.Load($1)`))
	source = embedPattern.ReplaceAll(source, []byte(`//go:embed ${1}.gz`))
	source, err := format.Source(source)
	return source, object, err
}

func pack(path string) error {
	source, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	source, object, err := rewrite(source)
	if err != nil {
		return err
	}
	object = filepath.Join(filepath.Dir(path), object)
	data, err := os.ReadFile(object)
	if err != nil {
		return err
	}
	if !bytes.HasPrefix(data, []byte("\x7fELF")) {
		return fmt.Errorf("%s: expected an ELF object", object)
	}
	var compressed bytes.Buffer
	w, err := gzip.NewWriterLevel(&compressed, gzip.BestCompression)
	if err != nil {
		return err
	}
	// Leave timestamp and filename empty for reproducible output.
	if _, err := w.Write(data); err != nil {
		return err
	}
	if err := w.Close(); err != nil {
		return err
	}
	if err := os.WriteFile(object+".gz", compressed.Bytes(), 0644); err != nil {
		return err
	}
	return os.WriteFile(path, source, 0644)
}

func run(patterns []string) error {
	if len(patterns) == 0 {
		return fmt.Errorf("usage: dae-bpf-pack <generated Go file patterns>")
	}
	for _, pattern := range patterns {
		paths, err := filepath.Glob(pattern)
		if err != nil {
			return err
		}
		if len(paths) == 0 {
			return fmt.Errorf("no generated files match %q", pattern)
		}
		for _, path := range paths {
			if !strings.HasSuffix(path, ".go") {
				return fmt.Errorf("%s: expected a Go source file", path)
			}
			if err := pack(path); err != nil {
				return fmt.Errorf("%s: %w", path, err)
			}
		}
	}
	return nil
}

func main() {
	if err := run(os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, "dae-bpf-pack:", err)
		os.Exit(1)
	}
}
