name: Go Test

on:
  pull_request:
    paths:
      - "**/*.go"
      - "**/*.c"
      - "**/*.h"
      - "control/kern/headers"
      - "trace/kern/headers"
      - ".gitmodules"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/go-test.yml"
      - "Makefile"
  push:
    branches:
      - next
    paths:
      - "**/*.go"
      - "**/*.c"
      - "**/*.h"
      - "control/kern/headers"
      - "trace/kern/headers"
      - ".gitmodules"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/go-test.yml"
      - "Makefile"

permissions: read-all

jobs:
  go-test:
    name: Go Unit Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          cache-dependency-path: |
            go.mod
            go.sum
          go-version: '>=1.27.0'

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y clang-15 llvm-15

      - name: Run tests
        run: make test CLANG=clang-15 STRIP=llvm-strip-15
